#!/usr/bin/env python3
"""
SDD闭环 Generator v2.0
从需求生成SDD文档、影响分析、测试用例、实施步骤
"""
import argparse, json, sys, re
from dataclasses import dataclass, field, asdict
from typing import Optional, List
from datetime import datetime

VERSION = "2.0.0"

# ============ Data Classes ============

@dataclass
class ImpactItem:
    type: str  # program, file, field
    name: str
    change_type: str  # add, modify, delete
    location: str
    description: str

@dataclass
class ProgramChange:
    program: str
    type: str  # new, modify, delete
    change_points: List[str]
    files_affected: List[str]
    complexity: str  # low, medium, high

@dataclass
class TestCase:
    id: str
    type: str  # positive, negative, boundary, regression
    title: str
    steps: List[str]
    expected: str
    priority: str  # high, medium, low

@dataclass
class ImplementationStep:
    step: int
    title: str
    tasks: List[str]
    program: Optional[str] = None
    status: str = "pending"

@dataclass
class SDD:
    title: str
    story: str
    background: str
    goals: List[str]
    scope: List[str]
    file_impacts: List[ImpactItem]
    program_impacts: List[ProgramChange]
    design: str
    test_strategy: str
    test_cases: List[TestCase]
    implementation_steps: List[ImplementationStep]
    created_at: str = field(default_factory=lambda: datetime.now().isoformat())

    def to_markdown(self) -> str:
        lines = [
            f"# SDD - {self.title}",
            f"\n**Story:** {self.story}",
            f"**Date:** {self.created_at}",
            "\n## 1. 概述",
            f"\n### 1.1 背景\n{self.background}",
            f"\n### 1.2 目标\n" + "\n".join(f"- {g}" for g in self.goals),
            f"\n### 1.3 范围\n" + "\n".join(f"- {s}" for s in self.scope),
            "\n## 2. 影响分析",
        ]
        if self.file_impacts:
            lines.append("\n### 2.1 文件/表影响")
            lines.append("| 文件/表 | 操作 | 位置 | 说明 |")
            lines.append("|--------|------|------|------|")
            for item in self.file_impacts:
                lines.append(f"| {item.name} | {item.change_type} | {item.location} | {item.description} |")
        if self.program_impacts:
            lines.append("\n### 2.2 程序影响")
            lines.append("| 程序 | 类型 | 改动点 | 复杂度 |")
            lines.append("|------|------|--------|--------|")
            for p in self.program_impacts:
                lines.append(f"| {p.program} | {p.type} | {', '.join(p.change_points)} | {p.complexity} |")
        lines.extend([
            "\n## 3. 设计方案",
            f"\n{self.design}",
            "\n## 4. 测试策略",
            f"\n{self.test_strategy}",
        ])
        if self.test_cases:
            lines.append("\n## 5. 测试用例")
            for tc in self.test_cases:
                lines.extend([
                    f"\n### 5.{tc.id} [{tc.type.upper()}] {tc.title}",
                    f"**Priority:** {tc.priority}",
                    f"\n**Steps:**\n" + "\n".join(f"{i+1}. {s}" for i, s in enumerate(tc.steps)),
                    f"\n**Expected:** {tc.expected}",
                ])
        if self.implementation_steps:
            lines.append("\n## 6. 实施步骤")
            for step in self.implementation_steps:
                lines.append(f"\n### Step {step.step}: {step.title}")
                for task in step.tasks:
                    lines.append(f"- [ ] {task}")
        lines.append(f"\n\n---\n*Generated by SDD闭环 v{VERSION}*")
        return "\n".join(lines)

    def to_impact_analysis(self) -> str:
        lines = ["# 影响分析报告", f"\n**Story:** {self.story}", f"**Date:** {self.created_at}", "\n## Summary"]
        lines.append(f"- Files impacted: {len(self.file_impacts)}")
        lines.append(f"- Programs impacted: {len(self.program_impacts)}")
        lines.append(f"- Test cases: {len(self.test_cases)}")
        lines.append(f"- Implementation steps: {len(self.implementation_steps)}")
        return "\n".join(lines)

    def to_implementation_steps(self) -> str:
        lines = ["# 实施步骤", ""]
        for step in self.implementation_steps:
            lines.append(f"## Step {step.step}: {step.title}")
            for task in step.tasks:
                lines.append(f"- [ ] {task}")
            lines.append("")
        return "\n".join(lines)

class SDDGenerator:
    def __init__(self):
        self.sdd: Optional[SDD] = None

    def from_story(self, story: str) -> SDD:
        """从 User Story 创建 SDD"""
        self.sdd = SDD(
            title=self._extract_title(story),
            story=story,
            background="",
            goals=self._extract_goals(story),
            scope=[],
            file_impacts=[],
            program_impacts=[],
            design="",
            test_strategy="",
            test_cases=[],
            implementation_steps=[]
        )
        return self.sdd

    def add_impact(self, file_impacts: List[ImpactItem] = None,
                   program_impacts: List[ProgramChange] = None):
        if self.sdd and file_impacts:
            self.sdd.file_impacts.extend(file_impacts)
        if self.sdd and program_impacts:
            self.sdd.program_impacts.extend(program_impacts)

    def generate_test_cases(self, template: str = "standard") -> List[TestCase]:
        """生成测试用例模板"""
        if not self.sdd: return []
        cases = []
        tc_id = 1
        # Positive test
        cases.append(TestCase(
            id=str(tc_id), type="positive",
            title="Happy path test",
            steps=["Step 1", "Step 2", "Step 3"],
            expected="Expected result",
            priority="high"
        ))
        tc_id += 1
        # Negative test
        cases.append(TestCase(
            id=str(tc_id), type="negative",
            title="Error handling test",
            steps=["Invalid input", "Verify error handling"],
            expected="Error message displayed",
            priority="medium"
        ))
        tc_id += 1
        # Boundary test
        cases.append(TestCase(
            id=str(tc_id), type="boundary",
            title="Boundary condition test",
            steps=["Edge case input"],
            expected="Handled correctly",
            priority="medium"
        ))
        return cases

    def generate_steps(self) -> List[ImplementationStep]:
        """生成实施步骤"""
        if not self.sdd: return []
        steps = [
            ImplementationStep(1, "前置准备", ["备份现有程序", "创建开发分支"]),
            ImplementationStep(2, "文件修改", ["修改文件定义", "编译测试"]),
            ImplementationStep(3, "程序修改", ["实现改动逻辑", "单元测试"]),
            ImplementationStep(4, "联调测试", ["集成测试", "回归测试"]),
            ImplementationStep(5, "上线", ["代码审查", "部署发布"]),
        ]
        return steps

    def _extract_title(self, story: str) -> str:
        if "I want to" in story:
            match = re.search(r'I want to (.+)', story)
            if match: return match.group(1).strip().title()
        if "want to" in story:
            match = re.search(r'want to (.+)', story)
            if match: return match.group(1).strip().title()
        return "Untitled SDD"

    def _extract_goals(self, story: str) -> List[str]:
        goals = []
        if "so that" in story:
            match = re.search(r'so that (.+)', story)
            if match: goals.append(match.group(1).strip())
        return goals if goals else ["待补充目标"]

def interactive_mode():
    print(f"SDD闭环 Generator v{VERSION} - Interactive Mode")
    print("=" * 50)
    story = input("请输入 User Story (或粘贴 Jira Story): ").strip()
    if not story:
        print("Error: Story is required")
        return
    gen = SDDGenerator()
    sdd = gen.from_story(story)
    sdd.test_cases = gen.generate_test_cases()
    sdd.implementation_steps = gen.generate_steps()
    print("\n" + sdd.to_markdown())

def main():
    ap = argparse.ArgumentParser(description=f'SDD闭环 Generator v{VERSION}')
    ap.add_argument('--story', help='User Story text')
    ap.add_argument('--interactive', action='store_true', help='Interactive mode')
    ap.add_argument('--template', action='store_true', help='Generate SDD template')
    ap.add_argument('--output', '-o', help='Output file')
    ap.add_argument('--format', choices=['markdown','json'], default='markdown', help='Output format')
    args = ap.parse_args()

    if args.interactive:
        interactive_mode()
        return

    if args.template:
        gen = SDDGenerator()
        sdd = gen.from_story("# Template Story")
        print(sdd.to_markdown())
        return

    if not args.story:
        ap.print_help()
        return

    gen = SDDGenerator()
    sdd = gen.from_story(args.story)
    sdd.test_cases = gen.generate_test_cases()
    sdd.implementation_steps = gen.generate_steps()
    output = sdd.to_markdown()
    if args.output:
        open(args.output, 'w').write(output)
        print(f"✅ Written to {args.output}")
    else:
        print(output)

if __name__ == '__main__':
    main()
